export const APP_ROUTE_CHANGED = 'APP_ROUTE_CHANGED';

export const APP_LOGIN = 'APP_LOGIN';
export const APP_LOGIN_SUCCESS = 'APP_LOGIN_SUCCESS';
export const APP_LOGIN_FAILURE = 'APP_LOGIN_FAILURE';

export const APP_LOGOUT = 'APP_LOGOUT';
export const APP_LOGOUT_SUCCESS = 'APP_LOGOUT_SUCCESS';
export const APP_LOGOUT_FAILURE = 'APP_LOGOUT_FAILURE';

export const USER_CREATE = 'USER_CREATE';
export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_CREATE_FAILURE = 'USER_CREATE_FAILURE';

export const USER_GET = 'USER_GET';
export const USER_GET_SUCCESS = 'USER_GET_SUCCESS';
export const USER_GET_FAILURE = 'USER_GET_FAILURE';

export const USER_GET_CURRENT = 'USER_GET_CURRENT';
export const USER_GET_CURRENT_SUCCESS = 'USER_GET_CURRENT_SUCCESS';
export const USER_GET_CURRENT_FAILURE = 'USER_GET_CURRENT_FAILURE';

export const USER_LIST = 'USER_LIST';
export const USER_LIST_SUCCESS = 'USER_LIST_SUCCESS';
export const USER_LIST_FAILURE = 'USER_LIST_FAILURE';

export const USER_UPDATE = 'USER_UPDATE';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE';

export const USER_DELETE = 'USER_DELETE';
export const USER_DELETE_SUCCESS = 'USER_DELETE_SUCCESS';
export const USER_DELETE_FAILURE = 'USER_DELETE_FAILURE';

export const USER_GRANT_ADMIN = 'USER_GRANT_ADMIN';
export const USER_GRANT_ADMIN_SUCCESS = 'USER_GRANT_ADMIN_SUCCESS';
export const USER_GRANT_ADMIN_FAILURE = 'USER_GRANT_ADMIN_FAILURE';

export const USER_REVOKE_ADMIN = 'USER_REVOKE_ADMIN';
export const USER_REVOKE_ADMIN_SUCCESS = 'USER_REVOKE_ADMIN_SUCCESS';
export const USER_REVOKE_ADMIN_FAILURE = 'USER_REVOKE_ADMIN_FAILURE';

export const TEAM_CREATE = 'TEAM_CREATE';
export const TEAM_CREATE_SUCCESS = 'TEAM_CREATE_SUCCESS';
export const TEAM_CREATE_FAILURE = 'TEAM_CREATE_FAILURE';

export const TEAM_GET = 'TEAM_GET';
export const TEAM_GET_SUCCESS = 'TEAM_GET_SUCCESS';
export const TEAM_GET_FAILURE = 'TEAM_GET_FAILURE';

export const TEAM_GET_CURRENT = 'TEAM_GET_CURRENT';
export const TEAM_GET_CURRENT_SUCCESS = 'TEAM_GET_CURRENT_SUCCESS';
export const TEAM_GET_CURRENT_FAILURE = 'TEAM_GET_CURRENT_FAILURE';

export const TEAM_LIST = 'TEAM_LIST';
export const TEAM_LIST_SUCCESS = 'TEAM_LIST_SUCCESS';
export const TEAM_LIST_FAILURE = 'TEAM_LIST_FAILURE';

export const TEAM_UPDATE = 'TEAM_UPDATE';
export const TEAM_UPDATE_SUCCESS = 'TEAM_UPDATE_SUCCESS';
export const TEAM_UPDATE_FAILURE = 'TEAM_UPDATE_FAILURE';

export const TEAM_DELETE = 'TEAM_DELETE';
export const TEAM_DELETE_SUCCESS = 'TEAM_DELETE_SUCCESS';
export const TEAM_DELETE_FAILURE = 'TEAM_DELETE_FAILURE';


